// This file is automatically generated via JAA ROM generator tool. DO NOT MODIFY! 
module test.class.jb (
input [15:0] addr ,
input read_en ,
output reg [7:0] data
);
always @ (read_en or addr)
begin
  case (addr)
    0 : data = 8'hca ;
    1 : data = 8'hfe ;
    2 : data = 8'hfa ;
    3 : data = 8'haa ;
    4 : data = 8'h00 ;
    5 : data = 8'h01 ;
    6 : data = 8'h00 ;
    7 : data = 8'h2a ;
    8 : data = 8'h00 ;
    9 : data = 8'h32 ;
    10 : data = 8'hff ;
    11 : data = 8'hff ;
    12 : data = 8'h00 ;
    13 : data = 8'h00 ;
    14 : data = 8'hff ;
    15 : data = 8'hff ;
    16 : data = 8'hff ;
    17 : data = 8'hff ;
    18 : data = 8'hff ;
    19 : data = 8'hff ;
    20 : data = 8'hff ;
    21 : data = 8'hff ;
    22 : data = 8'hff ;
    23 : data = 8'hff ;
    24 : data = 8'hff ;
    25 : data = 8'hff ;
    26 : data = 8'hff ;
    27 : data = 8'hff ;
    28 : data = 8'hff ;
    29 : data = 8'hff ;
    30 : data = 8'hff ;
    31 : data = 8'hff ;
    32 : data = 8'hff ;
    33 : data = 8'hff ;
    34 : data = 8'hff ;
    35 : data = 8'hff ;
    36 : data = 8'hff ;
    37 : data = 8'hff ;
    38 : data = 8'hff ;
    39 : data = 8'hff ;
    40 : data = 8'hff ;
    41 : data = 8'hff ;
    42 : data = 8'h00 ;
    43 : data = 8'h00 ;
    44 : data = 8'h00 ;
    45 : data = 8'h00 ;
    46 : data = 8'h00 ;
    47 : data = 8'h00 ;
    48 : data = 8'h00 ;
    49 : data = 8'h64 ;
    50 : data = 8'h11 ;
    51 : data = 8'h03 ;
    52 : data = 8'hff ;
    53 : data = 8'h3c ;
    54 : data = 8'h14 ;
    55 : data = 8'h00 ;
    56 : data = 8'h02 ;
    57 : data = 8'h41 ;
    58 : data = 8'hb1 ;
    default : data = 0;
  endcase
end

endmodule
